work in progress

diff --git a/interpolation/Makefile.in b/interpolation/Makefile.in
--- a/interpolation/Makefile.in
+++ b/interpolation/Makefile.in
@@ -72,7 +72,7 @@ full_top_srcdir = @full_top_srcdir@
 
 lib_LIBRARIES = libgslinterpolation.a 
 
-# check_PROGRAMS = test_interp
+check_PROGRAMS = test_interp
 
 include_HEADERS = 		\
 	gsl_interp.h
@@ -83,14 +83,15 @@ noinst_HEADERS = 		\
 
 INCLUDES = -I$(full_top_srcdir) -I$(full_top_srcdir)/err
 
-#TESTS = test_interp
+TESTS = test_interp
 
-#test_sf_LDADD = libgslinterpolation.a ../err/libgslerr.a ../err/libgsltest.a
-#test_sf_DEPENDENCIES = libgslinterpolation.a
-#test_sf_SOURCES = test_interp.c
+test_interp_LDADD = libgslinterpolation.a ../err/libgslerr.a ../err/libgsltest.a
+test_interp_DEPENDENCIES = libgslinterpolation.a
+test_interp_SOURCES = test_interp.c
 
 libgslinterpolation_a_SOURCES = 	\
 	accel.c				\
+	akima.c				\
 	bsearch.c			\
 	cspline.c			\
 	interp.c			\
@@ -107,9 +108,11 @@ CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
 libgslinterpolation_a_LIBADD = 
-libgslinterpolation_a_OBJECTS =  accel.o bsearch.o cspline.o interp.o \
-linear.o tridiag.o
+libgslinterpolation_a_OBJECTS =  accel.o akima.o bsearch.o cspline.o \
+interp.o linear.o tridiag.o
 AR = ar
+test_interp_OBJECTS =  test_interp.o
+test_interp_LDFLAGS = 
 CFLAGS = @CFLAGS@
 COMPILE = $(CC) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
 LINK = $(CC) $(CFLAGS) $(LDFLAGS) -o $@
@@ -122,10 +125,10 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP = --best
-DEP_FILES =  .deps/accel.P .deps/bsearch.P .deps/cspline.P \
-.deps/interp.P .deps/linear.P .deps/tridiag.P
-SOURCES = $(libgslinterpolation_a_SOURCES)
-OBJECTS = $(libgslinterpolation_a_OBJECTS)
+DEP_FILES =  .deps/accel.P .deps/akima.P .deps/bsearch.P .deps/cspline.P \
+.deps/interp.P .deps/linear.P .deps/test_interp.P .deps/tridiag.P
+SOURCES = $(libgslinterpolation_a_SOURCES) $(test_interp_SOURCES)
+OBJECTS = $(libgslinterpolation_a_OBJECTS) $(test_interp_OBJECTS)
 
 all: Makefile $(LIBRARIES) $(HEADERS)
 
@@ -191,6 +194,19 @@ libgslinterpolation.a: $(libgslinterpolation_a_OBJECTS) $(libgslinterpolation_a_
 	-rm -f libgslinterpolation.a
 	$(AR) cru libgslinterpolation.a $(libgslinterpolation_a_OBJECTS) $(libgslinterpolation_a_LIBADD)
 	$(RANLIB) libgslinterpolation.a
+
+mostlyclean-checkPROGRAMS:
+
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
+
+distclean-checkPROGRAMS:
+
+maintainer-clean-checkPROGRAMS:
+
+test_interp: $(test_interp_OBJECTS) $(test_interp_DEPENDENCIES)
+	@rm -f test_interp
+	$(LINK) $(test_interp_LDFLAGS) $(test_interp_OBJECTS) $(test_interp_LDADD) $(LIBS)
 
 install-includeHEADERS: $(include_HEADERS)
 	@$(NORMAL_INSTALL)
@@ -272,10 +288,35 @@ maintainer-clean-depend:
 	@-sed -e 's/^\([^:]*\)\.o:/\1.lo \1.o:/' \
 	  < .deps/$(*F).p > .deps/$(*F).P
 	@-rm -f .deps/$(*F).p
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info:
 dvi:
-check: all
-	$(MAKE)
+check: all $(check_PROGRAMS)
+	$(MAKE) check-TESTS
 installcheck:
 install-exec: install-libLIBRARIES
 	@$(NORMAL_INSTALL)
@@ -309,32 +350,36 @@ maintainer-clean-generic:
 	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
 	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
 mostlyclean:  mostlyclean-libLIBRARIES mostlyclean-compile \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+		mostlyclean-checkPROGRAMS mostlyclean-tags \
+		mostlyclean-depend mostlyclean-generic
 
-clean:  clean-libLIBRARIES clean-compile clean-tags clean-depend \
-		clean-generic mostlyclean
+clean:  clean-libLIBRARIES clean-compile clean-checkPROGRAMS clean-tags \
+		clean-depend clean-generic mostlyclean
 
-distclean:  distclean-libLIBRARIES distclean-compile distclean-tags \
-		distclean-depend distclean-generic clean
+distclean:  distclean-libLIBRARIES distclean-compile \
+		distclean-checkPROGRAMS distclean-tags distclean-depend \
+		distclean-generic clean
 	-rm -f config.status
 
 maintainer-clean:  maintainer-clean-libLIBRARIES \
-		maintainer-clean-compile maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean
+		maintainer-clean-compile maintainer-clean-checkPROGRAMS \
+		maintainer-clean-tags maintainer-clean-depend \
+		maintainer-clean-generic distclean
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
 .PHONY: mostlyclean-libLIBRARIES distclean-libLIBRARIES \
 clean-libLIBRARIES maintainer-clean-libLIBRARIES uninstall-libLIBRARIES \
 install-libLIBRARIES mostlyclean-compile distclean-compile \
-clean-compile maintainer-clean-compile uninstall-includeHEADERS \
+clean-compile maintainer-clean-compile mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS uninstall-includeHEADERS \
 install-includeHEADERS tags mostlyclean-tags distclean-tags clean-tags \
 maintainer-clean-tags distdir mostlyclean-depend distclean-depend \
-clean-depend maintainer-clean-depend info dvi installcheck install-exec \
-install-data install uninstall all installdirs mostlyclean-generic \
-distclean-generic clean-generic maintainer-clean-generic clean \
-mostlyclean distclean maintainer-clean
+clean-depend maintainer-clean-depend check-TESTS info dvi installcheck \
+install-exec install-data install uninstall all installdirs \
+mostlyclean-generic distclean-generic clean-generic \
+maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
 
 strict:
