work in progress

diff --git a/ieee-utils/Makefile.in b/ieee-utils/Makefile.in
--- a/ieee-utils/Makefile.in
+++ b/ieee-utils/Makefile.in
@@ -74,10 +74,13 @@ lib_LIBRARIES = libgslieeeutils.a
 include_HEADERS = gsl_ieee_utils.h
 
 libgslieeeutils_a_SOURCES = endian.c print-ieee.c standardize.c \
-	gsl_ieee_utils.h ieee_utils.h
+	make_rep.c gsl_ieee_utils.h ieee_utils.h
 
+INCLUDES = -I$(srcdir)/.. -I$(srcdir)/../err
+
+TESTS = test
 check_PROGRAMS = test
-test_LDADD = libgslieeeutils.a
+test_LDADD = libgslieeeutils.a ../err/libgsltest.a
 test_SOURCES = test.c
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = ../config.h
@@ -90,10 +93,11 @@ CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
 libgslieeeutils_a_LIBADD = 
-libgslieeeutils_a_OBJECTS =  endian.o print-ieee.o standardize.o
+libgslieeeutils_a_OBJECTS =  endian.o print-ieee.o standardize.o \
+make_rep.o
 AR = ar
 test_OBJECTS =  test.o
-test_DEPENDENCIES =  libgslieeeutils.a
+test_DEPENDENCIES =  libgslieeeutils.a ../err/libgsltest.a
 test_LDFLAGS = 
 CFLAGS = @CFLAGS@
 COMPILE = $(CC) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
@@ -107,8 +111,8 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP = --best
-DEP_FILES =  .deps/endian.P .deps/print-ieee.P .deps/standardize.P \
-.deps/test.P
+DEP_FILES =  .deps/endian.P .deps/make_rep.P .deps/print-ieee.P \
+.deps/standardize.P .deps/test.P
 SOURCES = $(libgslieeeutils_a_SOURCES) $(test_SOURCES)
 OBJECTS = $(libgslieeeutils_a_OBJECTS) $(test_OBJECTS)
 
@@ -270,10 +274,35 @@ maintainer-clean-depend:
 	@-sed -e 's/^\([^:]*\)\.o:/\1.lo \1.o:/' \
 	  < .deps/$(*F).p > .deps/$(*F).P
 	@-rm -f .deps/$(*F).p
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info:
 dvi:
 check: all $(check_PROGRAMS)
-	$(MAKE)
+	$(MAKE) check-TESTS
 installcheck:
 install-exec: install-libLIBRARIES
 	@$(NORMAL_INSTALL)
@@ -333,10 +362,10 @@ distclean-checkPROGRAMS clean-checkPROGRAMS \
 maintainer-clean-checkPROGRAMS uninstall-includeHEADERS \
 install-includeHEADERS tags mostlyclean-tags distclean-tags clean-tags \
 maintainer-clean-tags distdir mostlyclean-depend distclean-depend \
-clean-depend maintainer-clean-depend info dvi installcheck install-exec \
-install-data install uninstall all installdirs mostlyclean-generic \
-distclean-generic clean-generic maintainer-clean-generic clean \
-mostlyclean distclean maintainer-clean
+clean-depend maintainer-clean-depend check-TESTS info dvi installcheck \
+install-exec install-data install uninstall all installdirs \
+mostlyclean-generic distclean-generic clean-generic \
+maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
